### ISSUE TITLE
access_key有效期问题

### ISSUE THREAD

**Issue by xiguayuyichao** [QiE2035/gs_bili#2]
access_key有效期很短,看redme是需要重新触发一下,怎么重新触发呢,在登录界面点登录无效,我现在就是登一次获取一次

**Comment by QiE2035** [comment]
您开启 *记住密码* 了吗？您的 `access_key` 会变吗？我这边记得应该是不会变的

如果改变的话，那就只能每次都重新获取了

~~或者等某个大佬搞出直接登录的办法~~

**Comment by xiguayuyichao** [comment]
谢谢,开启记住密码可以使access_key不变,问题解决
