### ISSUE TITLE
命令失效

### ISSUE THREAD

**Issue by chenxiex** [QiE2035/gs_bili#3]
README中提供的命令`loginSuccess=(data)=>{console.log(JSON.parse(data))}`输入后回车，登陆，不会有任何输出。但是在开发者面板确实能找到一个POST请求返回了access_key的。

**Comment by chenxiex** [comment]
Manjaro Linux, Firefox浏览器。

**Comment by QiE2035** [comment]
我这边测试依旧正常，请确认您的浏览器和操作是否有误

**Comment by chenxiex** [comment]
> 我这边测试依旧正常，请确认您的浏览器和操作是否有误

我用firefox依然不行，但是用chromium测试就正常了。之前都可以的，最近Manjaro源的firefox有一次更新，可能改了些什么东西吧。影响也不大，用chromium或者直接看响应头就可以了。
